### ISSUE TITLE
CenterContainer is missing

### ISSUE THREAD

**Issue by tarasowski** [andrewvo89/mirotone-react#7]
Hi Andrew,

I hope you're doing well. I tried importing CenterContainer, but it seems to be missing as there is no exported CenterContainer in the module. Could you please check on this?

Thanks!

Best regards,

Dimi

**Comment by andrewvo89** [comment]
Hi @tarasowski,

Sorry for the confusion. `CenterContainer` was just a helper component I used inside the docs to layout the display of the `Centered` component from Mirotone. It is not actually a Mirotone component.

I have updated the docs so `CenterContainer` is not longer showing, but it's just a `div` with styles as a wrapper to showcase the `Centered` component. 

More details on this commit: https://github.com/andrewvo89/mirotone-react/commit/3daf7cf791bdbb371cf134633b15a354effbbf3b
